name: Build and Push Python App to ECR

env:
  ECR_REGISTRY: 012738153021.dkr.ecr.eu-west-1.amazonaws.com
  ECR_REPOSITORY: directories-admin-panel
  AWS_REGION: eu-west-1
  DEPLOYMENT_NAME: directories-admin-dp
  CONTAINER_NAME: directories-admin

on:
  push:
    branches: [dev, staging, main]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::012738153021:role/GitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

      - name: Build Docker image
        run: |
          docker build \
          --platform linux/amd64 \
          -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.ref_name }}-latest \
          -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.ref_name }}-${{ github.run_number }} .

      - name: Push Docker image to ECR
        run: |
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.ref_name }}-latest
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.ref_name }}-${{ github.run_number }}

    outputs:
      image_tag: ${{ github.ref_name }}-${{ github.run_number }}
      branch_name: ${{ github.ref_name }}

  deploy-to-eks:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: ${{ needs.build-and-push.outputs.branch_name }}

    steps:
      - name: Set environment-specific variables for deploy
        run: |
          if [ "${{ needs.build-and-push.outputs.branch_name }}" = "dev" ]; then
            echo "EKS_CLUSTER=4Sale" >> $GITHUB_ENV
            echo "AWS_ROLE=arn:aws:iam::576399160919:role/GitHubActionsDeployRole" >> $GITHUB_ENV
            echo "K8S_NAMESPACE=integration" >> $GITHUB_ENV
          elif [ "${{ needs.build-and-push.outputs.branch_name }}" = "staging" ]; then
            echo "EKS_CLUSTER=4sale-eks-stg" >> $GITHUB_ENV
            echo "AWS_ROLE=arn:aws:iam::967690639697:role/GitHubActionsDeployRole" >> $GITHUB_ENV
            echo "K8S_NAMESPACE=staging" >> $GITHUB_ENV

          elif [ "${{ needs.build-and-push.outputs.branch_name }}" = "main" ]; then
            echo "EKS_CLUSTER=4sale-eks-prod" >> $GITHUB_ENV
            echo "AWS_ROLE=arn:aws:iam::012738153021:role/GitHubActionsRole" >> $GITHUB_ENV
            echo "K8S_NAMESPACE=default" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure EKS access
        run: |
          aws eks update-kubeconfig \
            --name ${{ env.EKS_CLUSTER }} \
            --region ${{ env.AWS_REGION }}

      - name: Deploy to EKS
        run: |
          kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} ${{ env.CONTAINER_NAME }}=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ needs.build-and-push.outputs.image_tag }} \
            --namespace ${{ env.K8S_NAMESPACE }}